notifications:
  email:
    if: branch = master
    recipients:
      - tekeshwarsingh2000@gmail.com
    on_success: change
    on_failure: always
os:
  - linux
dist: bionic
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
env:
  - FLUTTER_VERSION=stable
# jobs:
#   allow_failures:
#     - env: FLUTTER_VERSION=beta
before_script:
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_VERSION
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
